title: "마음의 가장자리"
description: "시와 에세이, 그리고 일상의 문장을 기록하는 공간"
url: "https://day-fly.github.io"
baseurl: "/my-diary"
lang: "ko-KR"
timezone: "Asia/Seoul"

markdown: kramdown
permalink: /:year/:month/:day/:title/

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "me"
